---
functional:
  - В приложении должно присутствовать меню для более удобного начала игры. 
  - Пользователь должен иметь возможность выбирать уровень сложности игры, противника,  саму игру
  - Обеспечить пользователю возможность сдаться
  - Пользователь должен иметь возможность настраивать громкость звуков
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность поставить игру на паузу
  - Пользователь должен иметь возможность выбирать язык
